types:
  - build

build_tar:
  type: build
  script:
    - composer install
    - echo "<?php" >> config.php
    - echo "\$rootPath = '$ROOT_PATH';" >> config.php
    - echo "\$noPicSrc = $rootPath . '$NO_PIC_LOCATION';" >> config.php
    - mv web move_me_later
    - tar -zcf ~/image-creator-$(git log -n 1 | grep commit | cut -d ' ' -f 2).tar.gz .
    - echo "done!"