types:
  - build

build_tar:
  type: build
  script:
    - composer install
    - echo "<?php" >> config.php
    - echo "\$rootPath = '$ROOT_PATH';" >> config.php
    - echo "\$noPicSrc = $rootPath . '$NO_PIC_LOCATION';" >> config.php
    - echo "<IfModule mod_rewrite.c>" >> web/.htaccess
    - echo "Options +FollowSymLinks" >> web/.htaccess
    - echo "RewriteEngine On" >> web/.htaccess
    - echo "RewriteBase /" >> web/.htaccess
    - echo "RewriteCond %{REQUEST_URI} (\/out\/pictures\/)" >> web/.htaccess
    - echo "RewriteCond %{REQUEST_FILENAME} !-f" >> web/.htaccess
    - echo "RewriteRule (\.jpe?g|\.gif|\.png)$ scale-image-creator.php" >> web/.htaccess
    - echo "</IfModule>" >> web/.htaccess
    - rm composer.*
    - rm config_example.php
    - rm readme.md
    - rm .gitignore
    - rm .gitlab-ci.yml
    - tar -zcf ~/image-creator-$(git log -n 1 | grep commit | cut -d ' ' -f 2).tar.gz .