types:
  - build

build_tar:
  type: build
  script:
    - composer install
    - echo "<?php" >> config.php
    - echo "\$rootPath = '$ROOT_PATH';" >> config.php
    - echo "\$noPicSrc = $rootPath . '$NO_PIC_LOCATION';" >> config.php
    - rm composer.*
    - rm config_example.php
    - rm readme.md
    - rm .gitignore
    - rm .gitlab-ci.yml
    - tar -zcf ~/image-creator-$(git log -n 1 | grep commit | cut -d ' ' -f 2).tar.gz .